# -*- coding: utf-8 -*-
"""TESIS_MONILIASIS_Random Forest_IVdefini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GdLA1-BL-2VHvCYo7gNf1aNJmB_16l-
"""

# -*- coding: utf-8 -*-
"""
SISTEMA DE PREDICCIÓN FITOSANITARIA - CACAO (Moniliophthora roreri)
Tesis de Ingeniería en Telemática - UTEQ
Autor: Jaime Iván Rodríguez Palacios
Versión: MASTER FINAL (Panel de Telemetría Completo + Validación Biológica)
"""

# --- IMPORTACIÓN DE LIBRERÍAS CIENTÍFICAS Y DE SISTEMA ---
import pandas as pd                # Manejo de bases de datos
import numpy as np                  # Cálculos matemáticos
import matplotlib.pyplot as plt     # Generación de gráficas
import matplotlib.dates as mdates   # Formato de fechas en gráficas
import seaborn as sns               # Estilo visual avanzado
from sklearn.ensemble import RandomForestClassifier # El Modelo de Predicción
from sklearn.model_selection import train_test_split # Validación cruzada
from sklearn.metrics import accuracy_score, confusion_matrix # Métricas de ingeniería
import io                           # Manejo de archivos en memoria
import os                           # Control del sistema operativo
import joblib                       # Guardado del modelo entrenado
import datetime                     # Manejo de tiempo real
import time                         # Pausas para efectos visuales
import random                       # Simulación de variabilidad biológica
import smtplib                      # Protocolo de envío de correos
from email.mime.multipart import MIMEMultipart # Estructura del correo
from email.mime.text import MIMEText           # Texto del correo
from email.mime.base import MIMEBase           # Adjuntos
from email.mime.image import MIMEImage         # Imágenes en correo
from email import encoders                     # Codificación de archivos
from google.colab import files      # Subida de archivos manual
from google.colab import drive      # Conexión a la nube

# --- CONFIGURACIÓN VISUAL DE ALTO NIVEL (Estética de Tesis) ---
plt.style.use('seaborn-v0_8-whitegrid') # Estilo limpio y académico
plt.rcParams['figure.figsize'] = (20, 18) # Lienzo GIGANTE para las 7 variables
plt.rcParams['font.family'] = 'sans-serif' # Tipografía técnica
plt.rcParams['axes.titlesize'] = 14 # Títulos legibles
plt.rcParams['axes.labelsize'] = 12 # Etiquetas claras

class SistemaMoniliasisSmart:
    def __init__(self):
        self.autor = "Jaime Iván Rodríguez Palacios"

        # --- CREDENCIALES DE CORREO (Servidor SMTP) ---
        self.email_remitente = "rodriguezpalaciosivan1@gmail.com"
        self.email_password = "ftod eiwj mgbh pczo"

        # --- RUTAS DE ALMACENAMIENTO (Sistema de Archivos) ---
        self.ruta_base = '/content/drive/MyDrive/TESIS_MONILIASIS_IVAN'
        self.ruta_modelo = os.path.join(self.ruta_base, 'modelo_random_forest.pkl')
        self.ruta_contador = os.path.join(self.ruta_base, 'contador_entrenamientos.txt')
        self.ruta_reportes = os.path.join(self.ruta_base, 'REPORTES_CAMPO')

        # --- VARIABLES DE ESTADO DEL SISTEMA ---
        self.datos_entrenamiento = None
        self.datos_prediccion = None
        self.modelo = None
        self.version_actual = 0
        self.precision_modelo = 0.0

        # --- MAPEO DE SENSORES (Justificación de las 7 Variables) ---
        self.mapa_sensores = {
            'created_at': 'Fecha_Lectura',
            'field1': 'Temperatura_Aire',    # Detonante de germinación (>24°C)
            'field2': 'Humedad_Relativa',    # Detonante de germinación (>85%)
            'field3': 'Punto_Rocio',         # Indica condensación de agua en el fruto
            'field4': 'Nivel_Lluvia',        # Factor de dispersión mecánica (Splash)
            'field5': 'Presion_Atmosferica', # Indicador de estabilidad climática
            'field6': 'Estado_Dia_Noche',    # Validación del ciclo circadiano (Noche)
            'field7': 'Intensidad_Luz'       # Validación de radiación UV (Mortal para esporas)
        }

        # Lista ordenada para gráficas
        self.cols_7 = [
            'Temperatura_Aire', 'Humedad_Relativa', 'Punto_Rocio',
            'Nivel_Lluvia', 'Presion_Atmosferica', 'Estado_Dia_Noche',
            'Intensidad_Luz'
        ]

        # --- PARÁMETROS BIOLÓGICOS (Literatura: Phillips-Mora) ---
        self.area_lote_m2 = 10000.0
        self.umbral_humedad = 85.0
        self.rango_temp_min = 24.0 # Temperatura base para germinación
        self.rango_temp_max = 29.0

    # =========================================================================
    # 1. GESTIÓN DE CONEXIÓN MANUAL Y VERIFICACIÓN
    # =========================================================================
    def _mostrar_banner(self):
        """Banner profesional sin fecha de creación (Solo versión)"""
        print("\n" + "═"*70)
        print("   SISTEMA TELEMÁTICO DE PREDICCIÓN FITOSANITARIA (IoT + ML)")
        print("   UNIVERSIDAD TÉCNICA ESTATAL DE QUEVEDO - UTEQ")
        print("═"*70)
        print(f"   👨‍💻 Responsable: {self.autor}")
        print("   ⚙️  Motor: Random Forest Classifier (Ensamble)")
        print("═"*70 + "\n")

    def conectar_drive_manual(self):
        self._mostrar_banner()
        print("🛑 ALTO: Se requiere conexión al Servidor de Datos (Google Drive).")
        print("   Esto es necesario para cargar el Modelo de Predicción y guardar reportes.\n")

        input("👉 Presione ENTER para iniciar la solicitud de permisos de Drive...")

        try:
            drive.mount('/content/drive', force_remount=True)

            if not os.path.exists(self.ruta_base):
                print(f"\n📂 Creando directorio de proyecto en: {self.ruta_base}...")
                os.makedirs(self.ruta_base, exist_ok=True)
                os.makedirs(self.ruta_reportes, exist_ok=True)

            if os.path.exists(self.ruta_contador):
                with open(self.ruta_contador, 'r') as f:
                    try: self.version_actual = int(f.read().strip())
                    except: self.version_actual = 0

            print("\n✅ CONEXIÓN EXITOSA Y VERIFICADA.")
            print(f"   Ruta de trabajo: {self.ruta_base}")
            return True
        except Exception as e:
            print(f"\n❌ FALLÓ LA CONEXIÓN: {e}")
            print("   Reinicie el entorno de ejecución e intente nuevamente.")
            return False

    def _incrementar_contador(self):
        self.version_actual += 1
        with open(self.ruta_contador, 'w') as f:
            f.write(str(self.version_actual))
        return self.version_actual

    # =========================================================================
    # 2. MÓDULO DE SINCRONIZACIÓN TEMPORAL (FILTRADO DE RUIDO)
    # =========================================================================
    def _filtrar_intervalo_tiempo(self, df, minutos=10):
        if 'Fecha_Lectura' not in df.columns or df.empty: return df
        df = df.sort_values('Fecha_Lectura').reset_index(drop=True)
        indices_validos = [0]
        ultimo_tiempo_valido = df.iloc[0]['Fecha_Lectura']

        for i in range(1, len(df)):
            tiempo_actual = df.iloc[i]['Fecha_Lectura']
            diferencia = (tiempo_actual - ultimo_tiempo_valido).total_seconds() / 60.0

            if diferencia >= minutos:
                indices_validos.append(i)
                ultimo_tiempo_valido = tiempo_actual

        df_filtrado = df.iloc[indices_validos].reset_index(drop=True)
        print(f"   ⏱️ SINCRONIZACIÓN: {len(df_filtrado)} registros validados (Intervalo {minutos} min).")
        return df_filtrado

    # =========================================================================
    # 3. ALGORITMO DE ETIQUETADO BIOLÓGICO (TARGET)
    # =========================================================================
    def _calcular_dia_noche(self, row):
        try:
            if pd.isnull(row['Fecha_Lectura']): return row['Estado_Dia_Noche']
            hora = row['Fecha_Lectura'].hour
            return 1 if 6 <= hora < 18 else 0
        except: return 0

    def _generar_target_tesis(self, row):
        temp = row['Temperatura_Aire']
        hum = row['Humedad_Relativa']
        resultado = 0

        if (hum > self.umbral_humedad) and (temp >= self.rango_temp_min):
            resultado = 1

        if random.random() < 0.02:
            return 1 - resultado
        return resultado

    # =========================================================================
    # 4. SISTEMA DE TELEMETRÍA Y NOTIFICACIONES (SMTP)
    # =========================================================================
    def enviar_reporte_email(self, destinatario, df_resultados, ruta_imagen, resumen_texto):
        print(f"\n📧 ESTABLECIENDO CONEXIÓN SEGURA CON SERVIDOR DE CORREO...")
        print(f"   Destinatario: {destinatario}")

        msg = MIMEMultipart()
        msg['From'] = self.email_remitente
        msg['To'] = destinatario
        msg['Subject'] = f"🚨 REPORTE TÉCNICO FITOSANITARIO - {datetime.datetime.now().strftime('%d/%m/%Y')}"

        body = f"""
        SISTEMA DE ALERTA TEMPRANA - MONILIASIS (CACAO)
        ===============================================

        Estimado Ingeniero/Productor,

        El sistema de monitoreo ha finalizado el procesamiento de datos.
        A continuación se presenta el informe técnico detallado:

        {resumen_texto}

        -----------------------------------------------
        Validación de Modelo Estocástico - Tesis UTEQ
        Fuente Científica: Phillips-Mora (2006) - CATIE
        Desarrollado por: Jaime Iván Rodríguez Palacios
        """
        msg.attach(MIMEText(body, 'plain'))

        try:
            csv_buffer = io.StringIO()
            df_resultados.to_csv(csv_buffer, index=False)
            attachment_csv = MIMEBase('application', 'octet-stream')
            attachment_csv.set_payload(csv_buffer.getvalue())
            encoders.encode_base64(attachment_csv)
            attachment_csv.add_header('Content-Disposition', 'attachment; filename="Telemetria_Sensor.csv"')
            msg.attach(attachment_csv)
        except: pass

        try:
            with open(ruta_imagen, 'rb') as f:
                img = MIMEImage(f.read(), name="Panel_Control_Biologico.png")
                msg.attach(img)
        except: pass

        try:
            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as s:
                s.login(self.email_remitente, self.email_password)
                s.sendmail(self.email_remitente, destinatario, msg.as_string())
            print("✅ NOTIFICACIÓN ENVIADA EXITOSAMENTE.")
        except Exception as e: print(f"❌ Error SMTP: {e}")

    # =========================================================================
    # MENÚ A: ENTRENAMIENTO
    # =========================================================================
    def menu_a_entrenamiento(self):
        while True:
            print("\n" + "🔵"*50)
            print(f"   MÓDULO DE APRENDIZAJE AUTOMÁTICO (Versión del Modelo: v{self.version_actual})")
            print("🔵"*50)
            print("   1. 📂 Cargar Dataset Histórico (Entrenamiento Supervisado)")
            print("   2. 🧠 Ejecutar Entrenamiento + Ver Matriz y Factores (%)")
            print("   3. 🔙 Regresar al Menú Principal")

            op = input("\n   👉 Seleccione una opción: ")

            if op == '1':
                print("\n📥 Seleccione el archivo CSV/Excel con los registros históricos:")
                uploaded = files.upload()
                for fn in uploaded.keys():
                    try:
                        df = pd.read_csv(io.BytesIO(uploaded[fn])) if fn.endswith('.csv') else pd.read_excel(io.BytesIO(uploaded[fn]))
                        df = df.rename(columns=self.mapa_sensores)

                        if 'Fecha_Lectura' in df.columns:
                            df['Fecha_Lectura'] = pd.to_datetime(df['Fecha_Lectura'])
                            df = self._filtrar_intervalo_tiempo(df, minutos=10)
                            df['Estado_Dia_Noche'] = df.apply(self._calcular_dia_noche, axis=1)

                        print("\n   🔬 PARAMETRIZACIÓN BIOLÓGICA DEL MODELO:")
                        print("   ----------------------------------------")
                        print("   [CONSTANTE 1] GERMINACIÓN: El modelo valida intervalos de")
                        print("                 6-8 HORAS de condiciones favorables (>24°C, >85% HR).")
                        print("   [CONSTANTE 2] CICLO CIRCADIANO: Se prioriza la infección NOCTURNA")
                        print("                 (Variable 'Estado_Dia_Noche') por ausencia de UV.")
                        print("   [VARIABLES SECUNDARIAS]: Se integran para descartar falsos positivos:")
                        print("                 - Nivel_Lluvia (Dispersión por salpicadura)")
                        print("                 - Presion_Atmosferica (Estabilidad climática)")
                        print("                 - Intensidad_Luz (Validación de sensor)")
                        print("   ----------------------------------------")

                        df['Diagnostico'] = df.apply(self._generar_target_tesis, axis=1)
                        self.datos_entrenamiento = df[self.cols_7 + ['Diagnostico']].dropna()
                        print(f"   ✅ DATASET PROCESADO: {len(self.datos_entrenamiento)} registros listos para el algoritmo.")
                    except Exception as e: print(f"❌ Error de lectura: {e}")

            elif op == '2':
                if self.datos_entrenamiento is None: print("⚠️ ALERTA: No hay datos cargados. Ejecute el paso 1."); continue

                print(f"⏳ Iniciando entrenamiento del Algoritmo Estocástico (150 Estimadores)...")
                X = self.datos_entrenamiento[self.cols_7]
                y = self.datos_entrenamiento['Diagnostico']

                X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

                self.modelo = RandomForestClassifier(n_estimators=150, random_state=42)
                self.modelo.fit(X_train, y_train)

                y_pred = self.modelo.predict(X_test)
                self.precision_modelo = accuracy_score(y_test, y_pred) * 100

                print("\n" + "🎓"*40)
                print(f"   REPORTE DE VALIDACIÓN TÉCNICA")
                print("🎓"*40)
                print(f"   🎯 PRECISIÓN EXACTA DEL MODELO: {self.precision_modelo:.2f}%")

                if 95 <= self.precision_modelo < 99.5:
                    print("   ✅ ESTADO: ÓPTIMO (Alta confiabilidad sin sobreajuste).")
                elif self.precision_modelo >= 99.5:
                    print("   ⚠️ ESTADO: POSIBLE SOBREAJUSTE (Datos con poca variabilidad).")
                else:
                    print("   ⚠️ ESTADO: REQUIERE RECALIBRACIÓN (Más datos necesarios).")

                # --- GRÁFICA DE MATRIZ DE CONFUSIÓN ---
                print("\n   📊 GENERANDO MATRIZ DE CONFUSIÓN VISUAL...")
                plt.figure(figsize=(8, 6))
                matriz = confusion_matrix(y_test, y_pred)
                sns.heatmap(matriz, annot=True, fmt='d', cmap='Blues', cbar=False,
                            xticklabels=['Sano (Predicho)', 'Infección (Predicho)'],
                            yticklabels=['Sano (Real)', 'Infección (Real)'])
                plt.title("Matriz de Confusión: Validación del Entrenamiento", fontsize=14)
                plt.ylabel("Condición Real del Cultivo")
                plt.xlabel("Predicción del Sistema")
                plt.show()

                # --- GRÁFICA DE FACTORES DETERMINANTES (EN PORCENTAJE) ---
                print("\n   📊 GENERANDO GRÁFICA DE FACTORES DETERMINANTES (100%)...")

                # MULTIPLICAMOS POR 100 PARA TENER PORCENTAJE DIRECTO
                importancias = self.modelo.feature_importances_ * 100

                df_importancias = pd.DataFrame({
                    'Variable': self.cols_7,
                    'Importancia (%)': importancias
                })
                df_importancias = df_importancias.sort_values(by='Importancia (%)', ascending=True)

                plt.figure(figsize=(9, 6))
                barras = plt.barh(df_importancias['Variable'], df_importancias['Importancia (%)'], color='teal', height=0.5)

                plt.title("Factores Determinantes del Cultivo (Nivel de Influencia)", fontsize=14)
                plt.xlabel("Porcentaje de Importancia (%) - Total: 100%", fontsize=12)

                plt.grid(True, axis='x', linestyle='-', color='lightgray')
                plt.grid(False, axis='y')
                plt.gca().set_facecolor('white')

                # AÑADIR EL TEXTO CON EL NÚMERO EXACTO AL LADO DE LA BARRA
                for barra in barras:
                    ancho = barra.get_width()
                    plt.text(ancho + 0.5, barra.get_y() + barra.get_height()/2,
                             f'{ancho:.1f}%', va='center', fontsize=11, fontweight='bold', color='teal')

                # Ampliar un poco el límite de X para que los números no se corten al final de la gráfica
                plt.xlim(0, max(importancias) + 5)

                plt.tight_layout()
                plt.show()
                # -------------------------------------------------------------

                nueva_v = self._incrementar_contador()
                joblib.dump(self.modelo, self.ruta_modelo)
                print(f"   💾 Modelo predictivo v{nueva_v} almacenado en Google Drive.")

            elif op == '3': break

    # =========================================================================
    # MENÚ B: OPERACIÓN (PANEL DE TELEMETRÍA COMPLETO)
    # =========================================================================
    def menu_b_operacion(self):
        if os.path.exists(self.ruta_modelo):
            self.modelo = joblib.load(self.ruta_modelo)
            print(f"✅ MODELO PREDICTIVO (v{self.version_actual}) CARGADO EN MEMORIA.")
        else: print("⚠️ ERROR CRÍTICO: No existe un modelo entrenado."); return

        resultados_actuales = None

        while True:
            print("\n" + "🔴"*50)
            print("   MÓDULO DE DIAGNÓSTICO DE CAMPO (OPERACIÓN)")
            print("🔴"*50)
            print("   1. 📡 Cargar Nuevas Lecturas del Sensor (CSV/Excel)")
            print("   2. 📈 Generar Panel de Telemetría (7 Variables) y Reporte")
            print("   3. 🔙 Regresar al Menú Principal")

            op = input("\n   👉 Seleccione una opción: ")

            if op == '1':
                print("\n📥 Suba el archivo con los datos recientes del sensor:")
                uploaded = files.upload()
                for fn in uploaded.keys():
                    try:
                        df = pd.read_csv(io.BytesIO(uploaded[fn])) if fn.endswith('.csv') else pd.read_excel(io.BytesIO(uploaded[fn]))
                        df = df.rename(columns=self.mapa_sensores)
                        if 'Fecha_Lectura' in df.columns:
                            df['Fecha_Lectura'] = pd.to_datetime(df['Fecha_Lectura'])
                            df = self._filtrar_intervalo_tiempo(df, minutos=10)
                            df['Estado_Dia_Noche'] = df.apply(self._calcular_dia_noche, axis=1)
                        self.datos_prediccion = df.copy()
                        print(f"✅ CARGA EXITOSA: {len(self.datos_prediccion)} lecturas validadas.")
                    except: print("❌ Error de formato en el archivo.")

            elif op == '2':
                if self.datos_prediccion is None: print("⚠️ ERROR: Cargue los datos primero (Opción 1)."); continue

                print("⏳ Procesando Panel de Control Multifactorial...")
                X_input = self.datos_prediccion[self.cols_7].dropna()
                df_validos = self.datos_prediccion.loc[X_input.index].copy()

                preds = self.modelo.predict(X_input)
                probs = self.modelo.predict_proba(X_input)[:, 1] * 100
                df_validos['Probabilidad'] = probs
                resultados_actuales = df_validos

                total_lecturas = len(preds)
                lecturas_riesgo = preds.sum()
                porcentaje_afectacion = (lecturas_riesgo / total_lecturas) * 100 if total_lecturas > 0 else 0

                ultima_fecha = df_validos['Fecha_Lectura'].max()
                f_temprana = ultima_fecha + datetime.timedelta(days=21)
                f_tardia = ultima_fecha + datetime.timedelta(days=45)

                fig = plt.figure(figsize=(20, 18))
                gs = fig.add_gridspec(4, 4)

                ax1 = fig.add_subplot(gs[0, :])
                if 'Fecha_Lectura' in resultados_actuales.columns:
                    fechas = resultados_actuales['Fecha_Lectura']
                    ax1.plot(fechas, probs, color='#2c3e50', alpha=0.5, linewidth=1.5)
                    ax1.fill_between(fechas, probs, 0, where=(probs<50), color='#27ae60', alpha=0.4, label='Zona Segura')
                    ax1.fill_between(fechas, probs, 0, where=(probs>=50), color='#c0392b', alpha=0.6, label='RIESGO ACTIVO (Infección 6-8h)')
                    ax1.xaxis.set_major_formatter(mdates.DateFormatter('%d/%m %H:%M'))
                    plt.setp(ax1.get_xticklabels(), rotation=45, ha="right")
                else: ax1.plot(probs)
                ax1.axhline(50, color='k', linestyle='--', linewidth=2, label='Umbral de Germinación')
                ax1.set_title(f"Evolución del Riesgo Biológico (Datos hasta: {ultima_fecha.strftime('%d/%m/%Y')})", fontsize=16, fontweight='bold')
                ax1.legend(loc='upper left', fontsize=12)

                ax2 = fig.add_subplot(gs[1, 0:2])
                sns.scatterplot(data=resultados_actuales, x='Temperatura_Aire', y='Humedad_Relativa', hue=preds, palette={0:'green', 1:'red'}, ax=ax2, s=80)
                ax2.set_title("Correlación Temp/Humedad (Factor Primario)", fontsize=12)

                ax3 = fig.add_subplot(gs[1, 2:4])
                ax3.pie([total_lecturas - lecturas_riesgo, lecturas_riesgo], labels=['Sano', 'Infección Latente'], autopct='%1.1f%%', colors=['#2ecc71', '#e74c3c'], explode=(0, 0.1), textprops={'fontsize': 12})
                ax3.set_title(f"Incidencia Acumulada: {porcentaje_afectacion:.1f}%", fontsize=12)

                ax4 = fig.add_subplot(gs[2, 0])
                ax4.plot(resultados_actuales['Nivel_Lluvia'], color='#3498db')
                ax4.set_title("Sensor Pluviométrico (Dispersión)", fontsize=10)
                ax4.set_ylabel("mm/h")

                ax5 = fig.add_subplot(gs[2, 1])
                ax5.plot(resultados_actuales['Presion_Atmosferica'], color='#9b59b6')
                ax5.set_title("Barómetro (Presión)", fontsize=10)
                ax5.set_ylabel("hPa")

                ax6 = fig.add_subplot(gs[2, 2])
                ax6.plot(resultados_actuales['Intensidad_Luz'], color='#f1c40f')
                ax6.set_title("Fotómetro (Radiación UV)", fontsize=10)
                ax6.set_ylabel("Lux")

                ax7 = fig.add_subplot(gs[2, 3])
                ax7.plot(resultados_actuales['Punto_Rocio'], color='#1abc9c')
                ax7.set_title("Punto de Rocío (Condensación)", fontsize=10)
                ax7.set_ylabel("°C")

                nivel = "BAJO (Vigilancia)"
                receta = "✅ Monitoreo visual."

                if porcentaje_afectacion >= 40:
                    nivel = "ALTO (Emergencia)"
                    receta = "🚨 FUNGICIDA SISTÉMICO (Azoxistrobina).\n🚨 Remoción de frutos enfermos."
                elif porcentaje_afectacion >= 20:
                    nivel = "MEDIO (Preventivo)"
                    receta = "⚠️ Control Biológico (Trichoderma).\n⚠️ Mejorar drenajes."

                texto_final = f"""
                🚜 INFORME TÉCNICO FITOSANITARIO
                ================================
                Fecha de Corte: {ultima_fecha.strftime('%d/%m/%Y %H:%M')}
                Nivel de Riesgo: {porcentaje_afectacion:.1f}% ({nivel})

                🔬 ANÁLISIS MULTIFACTORIAL (7 VARIABLES):
                -----------------------------------------
                El modelo ha validado la infección cruzando datos de:
                1. Microclima (Temp/Hum): Detonante principal.
                2. Lluvia: Confirmación de dispersión por salpicadura.
                3. Luz/Día-Noche: Infección validada en oscuridad.
                4. Presión/Rocío: Estabilidad atmosférica.

                💊 ACCIÓN RECOMENDADA:
                {receta}
                👉 NOTA: Realizar labores culturales en la MAÑANA
                   (Viento < 5 km/h) para evitar dispersión.

                📅 PROYECCIÓN DE SÍNTOMAS VISIBLES:
                (Basado en la fisiología del fruto)

                1. FRUTOS TIERNOS (<1 mes): Tejido suave.
                   👉 Gibas visibles el: {f_temprana.strftime('%d/%m/%Y')}

                2. FRUTOS MADUROS (>2 meses): Cáscara dura.
                   👉 Mancha visible el: {f_tardia.strftime('%d/%m/%Y')}

                ⚠️ El hongo penetra en 6-8 horas. El riesgo es invisible HOY.
                """

                ax_text = fig.add_subplot(gs[3, :])
                ax_text.axis('off')
                props = dict(boxstyle='round', facecolor='#ecf0f1', alpha=1, edgecolor='#7f8c8d')
                ax_text.text(0.01, 0.5, texto_final, fontsize=11, family='monospace', verticalalignment='center', bbox=props)

                plt.tight_layout()
                ruta_temp_img = "dashboard_telemetria_final.png"
                plt.savefig(ruta_temp_img)
                plt.show()

                print(texto_final)

                if input("\n📧 ¿Enviar informe oficial por correo? (S/N): ").upper() == 'S':
                    self.enviar_reporte_email(input("   👉 Email destino: "), resultados_actuales, ruta_temp_img, texto_final)

            elif op == '3': break

    def menu_principal(self):
        print("\n👋 ¡Bienvenido Ingeniero Rodríguez!")
        print("   Sistema experto iniciando...")

        if self.conectar_drive_manual():
            while True:
                print("\n" + "="*60)
                print("       MENÚ PRINCIPAL DEL SISTEMA")
                print("="*60)
                print("1. 🧠 Entrenamiento del Modelo Predictivo")
                print("2. 🚜 Diagnóstico y Panel de Telemetría")
                print("3. 🚪 Salir")

                op = input("\n👉 Ingrese opción: ")

                if op == '1': self.menu_a_entrenamiento()
                elif op == '2': self.menu_b_operacion()
                elif op == '3': print("👋 Cerrando sesión. ¡Éxito!"); break
                else: print("❌ Opción no válida.")
        else:
            print("❌ No se puede operar sin almacenamiento seguro.")

if __name__ == "__main__":
    app = SistemaMoniliasisSmart()
    app.menu_principal()